### ISSUE TITLE
Bug: generateray not defined

### ISSUE THREAD

**Issue by alfredclwong** [microsoft/OpticSim.jl#166]
`generateray` was defined in the old Emitter.jl code but got deleted.

https://github.com/microsoft/OpticSim.jl/blob/de68aa75b5de4b0e9251e15b4a86bb77738443f2/src/Optical/Emitter.jl#L319-L329

It's used in the new emitter code and also in OpticalSystem.jl by `traceMT` and `tracehitsMT`. 

https://github.com/microsoft/OpticSim.jl/blob/c2e31018eb5fd369ce426ce906628484bb676d4d/src/Optical/Emitters/Origins.jl#L17
https://github.com/microsoft/OpticSim.jl/blob/c2e31018eb5fd369ce426ce906628484bb676d4d/src/Optical/OpticalSystem.jl#L429
https://github.com/microsoft/OpticSim.jl/blob/c2e31018eb5fd369ce426ce906628484bb676d4d/src/Optical/OpticalSystem.jl#L436
https://github.com/microsoft/OpticSim.jl/blob/c2e31018eb5fd369ce426ce906628484bb676d4d/src/Optical/OpticalSystem.jl#L536
https://github.com/microsoft/OpticSim.jl/blob/c2e31018eb5fd369ce426ce906628484bb676d4d/src/Optical/OpticalSystem.jl#L546

@galran: in Origins.jl, is it just meant to be a call to `Emitters.generate`? After looking at the code in more detail, I'm starting to think `Emitters.generate` could be replaced by `Base` iterator methods. Was there a reason you didn't do this?

@BrianGun: how about in OpticalSystem.jl?

**Comment by BrianGun** [comment]
looks like the new function generate(source,k::int) performs the same function as the old generateray, i.e., generate the kth ray in the sequence.

In OpticalSystem.jl generateray is used only in multithreaded trace functions traceMT and tracehitsMT. It's a simple way of distributing the rays evenly across the threads. Should be able to replace generateray with the new generate, or with indexing (see below).

looks like getindex in Origins.jl should be changed from this:
```
Base.getindex(a::AbstractOriginDistribution, index) = generateray(a, index)
```

to this:
```
Base.getindex(a::AbstractOriginDistribution, index) = generate(a, index-1)
```
@galran could you verify this is correct?


Then in the traceMT code we should be able to do this:
```
lt = trace(system, sources[k], test = test)
```

instead of this:
```
lt = trace(system, generateray(sources, k), test = test)
```

**Comment by alfredclwong** [comment]
It's still not fixed in OpticalSystem.jl. I think we're waiting on verification from @galran about the fix.

**Comment by galran** [comment]
generate was supposed to be the main interface to everything in emitters and also replace generatera - at least that was the goal.
