### ISSUE TITLE
Support more surface types in AxisymmetricOpticalSystem

### ISSUE THREAD

**Issue by alfredclwong** [microsoft/OpticSim.jl#176]
Currently we only support `:Object`, `:Image`, `:Stop` as surface types in our Axisymmetric Optical System. Would be good to get at least Zernike surfaces supported. This would require an extension to the DataFrame structure to support a large number of generic coefficients/parameters.

**Comment by alfredclwong** [comment]
@BrianGun @friggog

I'm making some pretty significant changes in [asos-surfaces](https://github.com/microsoft/OpticSim.jl/tree/alfred/asos-surfaces), so I just wanted to check that they're OK.

1. Rename Surface column to SurfaceType
2. Use strings instead of symbols for SurfaceTypes, and change all enumerated surfaces to "Standard"
3. Remove "Object" surface type
4. Replace Aspheric/Conic surface columns with a generic Parameter column, which is accessed according to the SurfaceType

**Comment by friggog** [comment]
These all sound reasonable to me

Definitely agree with 1, don't want confusion with the Surface abstract type used elsewhere

What's the particular motivation for 2?

Can't even remember what Object is for...

Continuing from 4 - it would be nice to make this extensible at no cost, i.e. don't hard code what surface types/parameters are supported or not, then if a new surface type is added we can just include it and give it the right parameters without changing any of the code for AxisymmetricOpticalSystem itself

**Comment by BrianGun** [comment]
I agree with @friggog wrt 2, there is no advantage to using strings instead of symbols. Strings are a little harder to type. It's trivial to get a string from a Symbol, and println strips the leading : from Symbols so they print nicely. I vote we stick with Symbols.

The Object surface type represents the physical object the lens is focusing on, or at least the plane that is the source of rays entering the lens. This is a Zemax convention so if we change it that will make it more difficult for people to switch between Zemax and OpticSim.

**Comment by BrianGun** [comment]
Symbols vs. strings: won't strongly argue one way or the other. 

> ### Object surface type
> I asked Andreas and Mario about `Object` and they said that it was more of an annotation reflecting historical optical design pipelines. Also, in Zemax, `Object` is not actually the Surface Type - it's a label to the side of it. Correct me if I'm wrong, but it seems that `Object` and `Image` are simply conventions used to refer to the first and last surface in the Sequential lens design. However, if `Standard` doesn't actually mean anything for these surfaces, we can stick with the current scheme.
> 

For the image plane Standard can be useful if you want to make the Radius something other than infinity, i.e., to make the imager curved. Not sure if this has any meaning for the Object field. Never tried it and can't start my version of Zemax right now because somebody else has the license checked out.

**Comment by alfredclwong** [comment]
One last question: my understanding of the current code is that the semidiameter of the axisymmetric optical system is defined as the semidiameter of the first optical element, excluding stops. Is this correct, or should we also include stops if they are the first element?

**Comment by friggog** [comment]
I think the semidiameter is primarily (/only?) used for zemax-style fields which distribute rays evenly over the entrance pupil of the system for optimization (and visualization). In this case it would be reasonable to use the stop diameter as the entrance pupil if it is the first element in the system (providing the aperture is circular which it must be in an axisymmetric system - not sure how/if this is enforced atm?)
