### ISSUE TITLE
Permission denied when trying out example

### ISSUE THREAD

**Issue by dalanicolai** [microsoft/OpticSim.jl#202]
When trying to run the notebook using:
`NB.run_sample("EmittersIntro.jl")`
as described [on the example page](https://microsoft.github.io/OpticSim.jl/dev/examples/),
instead of opening the notebook, I get the message
`SystemError: opening file "/home/dalanicolai/EmittersIntro.jl": Permission denied`.

The new copy of the notebook file only has reading permissions. If I quickly add writing permissions with `sudo chmod u+w`
before the notebook gets opened by the pluto server, then the file opens normally (and tells me: `UndefVarError: default_resolution not defined`)

1.  Go to GNU/linux (Fedora 34)
2. Visit https://microsoft.github.io/OpticSim.jl/dev/examples/
3. Try to evaluate the first two lines of the example code

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Julia version 1.6.0
 - OpticSim.jl version v0.5.1

**Comment by dalanicolai** [comment]
I am not sure if I should open new issues for this, but while the notebook is running I also see the following message in the REPL
```
Warning: Can't initialize the JSServe package
│ ArgumentError("Package OpticSim does not have JSServe in its dependencies:\n- If you have OpticSim checked out for development and have\n  added JSServe as a dependency but haven't updated your primary\n  environment's manifest file, try `Pkg.resolve()`.\n- Otherwise you may need to report an issue with OpticSim")
```
Running `Pkg.resolve()` has no effect.

Also, to make the notebook load successfully, I additionally had to install the packages `PlutoUI` and `DataFrames`

**Comment by BrianGun** [comment]
@dalanicolai 

I'll look into this. We may be missing some packages in our project.toml file. Not sure why the notebook isn't running for you. Will try to reproduce on my end.

**Comment by BrianGun** [comment]
I'm running Linux Mint 19.2. Executed the first two lines from the examples documentation. Got the same `can't initialize JSServe package` but the notebook opened and displayed correctly except for the last example. We must have changed a function because this example no longer works. I'll open a separate issue.

Adding JSServe as a dependency gets rid of the  `can't initialize JSServe package` warning. I'll do this fix soon.

Not sure why you had to install `PlutoUI` and `DataFrames` and `Makie`. Those packages are dependencies in the Project.toml file. They should have been installed automatically.

Did not get the permission error that you described: `SystemError: opening file "/home/(your name here)/EmittersIntro.jl": Permission denied`. Maybe this is something unique to your machine configuration and its interaction with Julia or OpticSim.jl?
