### ISSUE TITLE
Support for odd aspheric terms

### ISSUE THREAD

**Issue by mattderstine** [microsoft/OpticSim.jl#291]
How do I enter an aspheric lens that has even and odd aspheric terms?  For example US Patent 7535658

**Comment by friggog** [comment]
Hey - the aspheric surface is actually implemented indirectly through the [zernike surface](https://github.com/microsoft/OpticSim.jl/blob/main/src/Geometry/Primitives/Zernike.jl) which was intended to match zemax for interoperability, hence only including the even terms. 

The easiest way is probably to add a dedicated aspheric surface which also allows for odd terms - all the code is already there as part of the zernike surface so it should be pretty straightforward to cut out the relevant bits and allow odd terms as well. Alternatively the odd terms could be added to the existing zernike surface - I’m not sure if Brian is still prioritising zemax interop or not as to whether this would be the right choice. It would require fewer code changes but potentially break more stuff

**Comment by mattderstine** [comment]
Thanks! Zemax does allow you to enter both even and odd aspheres (look up Extended Odd Asphere,for details). However, it does have a dedicated even asphere surface that I expect is there for better performance with most designs. 

I appreciate the your timely answer even it just confirms my quick review of the code. I'll put something simple together for my code and the issue if it belongs in OpticSim can be for another time.

**Comment by mattderstine** [comment]
It is relatively simple to modify zernikesurface to accept even and odd terms at the cost of about 2x more multiplies to evaluate the surface compared to even or odd sets of terms.  The normal approach would be to define surfaces as EvenAsphere, OddAsphere or OddEvenAsphere depending on the preference of the user.

It seems that it would be strange to create functions for zernikeEvenSurface, zernikeOddSurface and zernikeOddEvenSurface when most people won't be using the zernike terms on the surface.  What are the issues with:
1. Modifying ZernikeSurface to accept even and odd terms so that nothing breaks and the general asphere case is included someplace 
2. Adding EvenAsphere and OddAsphere surfaces and their ancillary functions, without the Zernike terms, that are optimized to get that 2X back.
3. Modifying AxisymmetricOpticalSystem to accept EvenAspheric, OddAspheric as additional surface types and have Aspheric refer to the ZernikeSurface with Odd & Even terms.  Nothing would break this way although current code would see a performance penalty unless the surface type is changed to EvenAspheric.

As an alternative it might be possible to define alternate methods for ZernikeSurface that handle the different options for Even, Odd and both, but this risks complexity with achieving good performance of methods like point(::ZernikeSurface) during raytracing.

Before I start to write something that can be used for more people than me, I'd like to make sure I'm pointed in the right direction.

**Comment by friggog** [comment]
Probably the best design would be:

- Add an `AsphericSurface` type which handles spherical, conic and aspheric terms _only_ - both even and odd. You can save on multiplication by iterating over only the defined terms rather than all of them, meaning adding the capacity for more terms doesn't add more (eg 2x) the operations - this is actually what `ZernikeSurface` does now.
- [Optionally] Add `EvenAsphericSurface` and `OddAsphericSurface` functions which just build an `AsphericSurface` under the hood
- Modify `ZernikeSurface` to have an `AsphericSurface` as a field, and use the `point` method from this to get the base component of the height, then add the zernike terms - with the same idea for `partials`. Not looking at the maths right now but I'm pretty sure they can be split up in this way. This way we reduce code duplication between the new `AsphericSurface` and `ZernikeSurface`. This is how the [`GridSag`](https://github.com/microsoft/OpticSim.jl/blob/main/src/Geometry/Primitives/GridSag.jl) surface works. As you say, it would be great to keep the constructor for `ZernikeSurface` compatible with existing code, and add odd aspheric terms as a separate argument perhaps, or with a different constructor function.
- Modify `AxisymmetricOpticalSystem` as you suggest

Writing performant code in Julia certainly isn't simple so I'm very happy to review your changes and help make sure it will work well for more people to use it. I'm not officially on this project any more or I would have the time to write the code myself - but definitely happy to review any PRs you make!

**Comment by mattderstine** [comment]
Thanks! Before I start coding, I wanted to check on the approach to computing the aspheric contributions. The code in `Point` for doing this is a new approach to me. I put together these test functions to understand the relative performance for each way. I'm new to this so I was wondering if anyone could run this test on real workstation (I'm only using a MacBookPro with 8 cores) and inform me on the results.

My results. (CurrentEven is the algorithm currently coded in `Point(::ZernikeSurface)`:
```
timing tests
CurrentEvenOdd      0.056010 seconds (7 allocations: 312 bytes)
CurrentEven         0.025671 seconds (7 allocations: 312 bytes)
incrementalEvenOdd  0.007436 seconds (7 allocations: 328 bytes)
incrementalEven     0.004759 seconds (7 allocations: 312 bytes)
0.07362918937067071   0.07362918937067071   0.07362918937067071   0.07362918937067071
```

This suggests that the more traditional method of computing the aspheric sag is faster and the use of even (or odd) only would be about a 2X speedup. I'd like to have some samples from more sophisticated processors or perhaps more aggressive compiler optimizations before making lots of changes.

Thanks!

```
using Random

function currentEvenOddTest(num)
    aspherics = [(4, 3.68090959e-7), (6, 2.73643352e-11), (8, 3.20036892e-14)]  #from one of the examples
    h=0.0
    Q = length(aspherics)
    Random.seed!(1234)
    for i in 1:num
        r = rand()
        @inbounds @simd for i in 1:Q
            (m, k) = aspherics[i]
            h += k * r^m
        end
    end
    print("CurrentEvenOdd    ")
    h
end

function currentEvenTest(num)
    asphericsEven = [(2, 3.68090959e-7), (3, 2.73643352e-11), (4, 3.20036892e-14)] #m is 1/2 aspheric term
    h=0.0
    Q = length(asphericsEven)
    Random.seed!(1234)
    for i in 1:num
        r = rand()
        r2 = r*r
        @inbounds @simd for i in 1:Q
            (m, k) = asphericsEven[i]
            h += k * r2^m
        end
    end
    print("CurrentEven       ")
    h
end

function incrementalEvenOddTest(num)
    asp = [0.0, 3.68090959e-7, 0.0, 2.73643352e-11, 0.0, 3.20036892e-14]
    h=0.0
    Random.seed!(1234)
    for i in 1:num
        r = rand()
        prod = r*r  #starts with A3 term
        @inbounds for k in asp
            prod *= r
            h += k * prod
        end
    end
    print("incrementalEvenOdd")
    h
end

function incrementalEvenTest(num)
    aspE = [3.68090959e-7, 2.73643352e-11, 3.20036892e-14]
    h=0.0
    Random.seed!(1234)
    for i in 1:num
        r = rand()
        r2 = r*r
        prod = r2
        @inbounds for k in aspE
            prod *= r2
            h += k * prod
        end
    end
    print("incrementalEven   ")
    h
end

@time currentEvenTest(1)  #make sure everything is initalized for the timing tests
println("timing tests")
hcEO=@time currentEvenOddTest(1000000)
hCE = @time currentEvenTest(1000000)
hiEO = @time incrementalEvenOddTest(1000000)    
hiE = @time incrementalEvenTest(1000000)
println("$hcEO   $hCE   $hiEO   $hiE")

```

**Comment by friggog** [comment]
It's hard to tell exactly what the issue is with just these bits in isolation - seems like the type here `aspherics::Vector{Tuple{Int64, Float64}}` is the issue, generally just having `Vector{T}(eacs)` won't cast the type correctly if `eacs` has the wrong type (ie a tuple). If you can open a PR (pull request) so I can see all the changes that would be the easiest way to review and work out the issue, and I can comment on specific lines of code then too
