### ISSUE TITLE
GlassCat tests

### ISSUE THREAD

**Issue by alfredclwong** [microsoft/OpticSim.jl#37]
Working on incorporating these into the main test code as a test set.

**Comment by alfredclwong** [comment]
A regression test is failing here. @BrianGun, @friggog, do either of you remember changing GlassCat.absorption?

https://github.com/microsoft/OpticSim.jl/blob/81fc799bd73edb964e848b532cd3cf46ef79300b/test/testsets/GlassCat.jl#L177-L181

```
  Expression: OpticSim.GlassCat.absorption(g, 500 * u"nm") == 0.00016032085590155288
   Evaluated: 0.0002407228930225164 == 0.00016032085590155288
  Expression: OpticSim.GlassCat.absorption(g, 600 * u"nm") == 0.00015028195510849153
   Evaluated: 0.00022060722752440445 == 0.00015028195510849153
  Expression: OpticSim.GlassCat.absorption(g, 3000 * u"nm") == 0.022484756726141652
   Evaluated: 0.04086604990127926 == 0.022484756726141652
  Expression: OpticSim.GlassCat.absorption(g, 600 * u"nm", temperature = 35 * u"°C", pressure = 2.0) == 0.0001502079956238452
   Evaluated: 0.00022075540719494738 == 0.0001502079956238452
```

**Comment by friggog** [comment]
It's most likely the AGF files changing?

**Comment by alfredclwong** [comment]
I think I've kept the same TEST_CAT.agf, but the GlassCat tests have been down for a while so maybe something changed. If Brian hasn't changed it either then I'll just update the values with what I'm seeing now.

**Comment by friggog** [comment]
These ones are testing on `OpticSim.GlassCat.SCHOTT.N_BK7` rather than TEST_CAT so it's quite possible the SCHOTT catalog has changed. I would be surprised if there were any code changes affecting this. You can compare the current SCHOTT AGF file to the old one and it might be obvious. If that's the case then it's probably safe just to recalculate these values and update the tests with the values for the new AGF file.

**Comment by alfredclwong** [comment]
Ah I was looking at the first value of `g = TEST_CAT.MG523`, thanks.
