### ISSUE TITLE
Installation problem: "Package Luxor does not have LaTeXSt"

### ISSUE THREAD

**Issue by hadmack** [microsoft/OpticSim.jl#370]
I have followed the instruction in the documentation to install Julia and OpticSim.jl. The examples will not run and I get the following error when loading the package:

Run Pluto and open a new Notebook
> import OpticSim.NotebooksUtils as NB
Error requiring `LaTeXStrings` from `Luxor`
"Package Luxor does not have LaTeXSt" ⋯ 226 bytes ⋯ "need to report an issue with Luxor"

 - OS: Windows 10
 - Julia version 1.7.2
 - OpticSim.jl version 0.5.3

This is my first time using Julia, so my environment is pristine and I followed the installation instructions carefully. I presume that this is a package dependency conflict but it could be user error. Please advise.

**Comment by BrianGun** [comment]
The Latex issue with Luxor is a problem with the Luxor package.  We raised the issue with them a while back and they said they would have a fix soon but it's still a problem. You can file a bug report at their github repo.

Examples not running is probably due to problems downloading the Schott glass catalog. They are constantly changing their website so our code can't find the download. We've fixed this in the code on our repo but not yet for the code in the Julia repo. We have to make a new release. 

If you clone the repo instead of adding the package from the Julia Registry then the examples should work. If they don't let me know and I'll fix them.

**Comment by rambunctiousapple** [comment]
@hadmack did this fix your problem? If it did I'll close the issue.

**Comment by BrianGun** [comment]
@hadmack Since this is a Luxor problem and not an OpticSim problem I'm closing the issue.
