### ISSUE TITLE
Synergy with other base packages for geometric processing

### ISSUE THREAD

**Issue by juliohm** [microsoft/OpticSim.jl#42]
We are working actively on [Meshes.jl](https://github.com/JuliaGeometry/Meshes.jl) to put together a project-independent set of geometry and mesh types. It would great to hear your point of view regarding reusing such projects as dependencies instead of developing separate geometry and mesh types. We are also MIT so license-wise there shouldn't be any issue.

The advantage of reusing a common codebase should be clear. If we all share a common set of primitives and mesh types, we can quickly integrate different ecosystems in Julia for visualization, finite element analysis, geospatial sciences, etc.

**Comment by BrianGun** [comment]
Whenever possible we leverage existing Julia packages. It's a great idea not to reinvent the wheel.

The majority of the optical surfaces we currently support are polynomials of various types: Bezier and NURBS patches, QType, Zernike, and Chebyshev polynomials. We don't approximate these surfaces by polygon meshes for the ray tracing; for the precision required in optical analysis a very high degree of triangulation would be necessary. Instead of triangulating the surfaces we compute ray surface intersections directly with the analytic surface representation, which is much more memory efficient.

These surfaces all have hand written partial functions with respect to the two parametrizing variables, so we can compute surface normals in a generic way, and for the Newton iteration intersection algorithm.  The partial functions must be as efficient as possible because they are called in the tightest part of the ray tracing loop.

Does Meshes.jl currently support these surface types, and associated functions? I looked at the docs and it didn't seem to. Would it make sense to add them or does that not fit with the goals of the Meshes.jl project?

**Comment by juliohm** [comment]
We are mostly working on polygonal meshes because there are some applications in other ecosystems driving this development. I think OpticSim.jl could be the application driving the development of the other primitives you mentioned. It would make total sense to add such functionality there. Contributions are more than welcome ❤️ 

Would you like to discuss over there in a GitHub issue? There are other contributors who may help shape the design as we move forward. It is been a really great experience to interact with people from different backgrounds to accommodate different applications.

**Comment by BrianGun** [comment]
Julio,

when you say "add such functionality there" and "discuss over there" does "there" refer to the Meshes.jl repo? That's the way I'm parsing it but want to make sure that's correct. 

Are you proposing we take the surface functionality out of OpticSim and move it into Meshes? Certainly worth having a discussion about.

**Comment by juliohm** [comment]
Sorry for the lack of accurate terms. Yes, I meant the Meshes.jl repository. If you feel that it is reasonable to migrate some of the geometric components from OpticSim.jl to Meshes.jl, we can write down a plan in the format of a GitHub issue. Would that be interesting to you?

**Comment by friggog** [comment]
Just to add that CAD file IO is perhaps the most valuable feature that this might bring about. A package supporting this in Julia would be great and if it uses our existing surface representation then that’s even better! 

I imagine most surfaces would have to be stored as NURBS in standard CAD formats so some fitting might be necessary for other polynomials. I think CSG should be broadly compatible but may also be a challenge.

**Comment by BrianGun** [comment]
moved this discussion to meshes.jl so closing this issue.
