### ISSUE TITLE
Sequential raytracing

### ISSUE THREAD

**Issue by cdhf** [microsoft/OpticSim.jl#63]
I need sequential raytracing for this package to be useful for my day job, so I would like to take a shot at implementing it.
I would love to have some advice on how to get started with this. I've never before contributed much to an open source project, so I may have some beginner's questions when it comes to the processes for contributing.

**Comment by BrianGun** [comment]
Look at OpticSim/src/Optical/LensAssembly.jl line 345 for a trace function that you should be able to modify for sequential tracing.

This trace function takes a LensAssembly as an argument. You would replace this argument with a list of surfaces (interface for surfaces defined in OpticSim/src/Geometry/Surface.jl). 

The rest of the code should remain quite similar. Similar enough, in fact that we may want to look at combining sequential and non-sequential tracing into a single function when you are done.

The real difference would be in the constructors for sequential systems. In the current system all optical elements are CSG trees, representing halfspaces, with a clearly defined inside and outside. 

The new sequential system will only have surfaces, many of which will not have clearly defined inside and outside. They will have a well defined normal, which is used when you assign an optical interface to the surface. This has two material types, one for the positive normal side of the surface, which is the outside material, and one for the negative normal side which is the inside material.

to make a simple spherical lens with two surfaces you'd need a list with two Sphere objects, one for the front and one for the back surface.

You could start with simple surfaces, such as sphere and cylinder, which take an optical interface as an argument to the constructor.

The polynomial surfaces are not created directly. Instead they are wrapped in an AcceleratedParametricSurface object (OpticSim/src/Geometry/AccelSurface.jl line 34), which takes as one argument the actual surface type, such as Zernike, Qtype, etc. and as another argument the optical interface for the surface.

The optical interface is stored in the AcceleratedParametricSurface object and used by the processintersection function to compute new ray directions for rays refracting or reflecting off a surface.

After you are comfortable with a linear list we could talk about extending this a DAG, which is useful in many cases, e.g., multiple detectors, many small lenses focusing light through a single large lens, and so forth. If you have any questions don't hesitate to ask.

**Comment by BrianGun** [comment]
I would recommend using VSCode and installing the Julia language extension and the github pull requests and issues extension, if you haven't already. These two together will make your life easier when you are ready to issue pull requests.

**Comment by cdhf** [comment]
I have now looked at the code and set up a simple single spherical lens system, both as a NSC system and a sequential system. I implemented the surfaces as a Vector{Tuple{T, Surface}}, where the first element is the distance to the previous surface. 

The first issue I have is that for spherical surfaces I cannot make the radius of curvature negative. I ignore this for now by using only positive radii because I do not want to mess with some invariant assumption in the code.

I then modified the trace function to call the surfaceintersection function on the first surface instead of closestintersection on the whole list, hoping that this would give allow me to reuse the already existing code. This does not work, however. I suspect that this is a coordinate system issue?

I also think that I have not quite understood the coordinate system in nonsequential tracing. I made a lens like this: 
`SphericalLens(N_BK7, 200.0, 40.0, 400.0, 15.0, 20.0)`
With Zemax prejudice I expected a convex/concave lens with the strongly curved surface towards z=0 to the right and its vertex at z=200. When I plot this lens, however, the lens is flipped around and the vertex of the strongly curved surface is at 215 mm. Is there a description of the coordinate system conventions in the documentation? I haven't found anything.

**Comment by friggog** [comment]
Awesome to hear of the progress on this!

For negative curvature use spherical cap. I imagine for sequential ray tracing it might be preferable to use the surfaces directly rather than creating 3D csg objects like that from the SphericalLens function.

your trace modification sounds sensible and should work in general, just tracing the first in the list of remaining elements - I think our z axis might be  inverted compared to zemax, you’re right that we should document this more clearly

**Comment by BrianGun** [comment]
@cdhf could you post your code here? That would help us understand what the issues are. 

I am guessing the confusion about how to make a negative curvature spherical surface may come from a misunderstanding of how the ray tracer works internally and how surfaces are represented.

Because OpticSim is designed from the ground up
Does Zemax use a left handed coordinate system for representing the lens coordinate frame? We are strictly right handed. Perhaps that is why things look backward to you.

When I execute this

lens = SphericalLens(SCHOTT.N_BK7, 200.0, 40.0, 400.0, 15.0, 20.0) 
Vis.draw(lens)

here is what I get:

![image](https://user-images.githubusercontent.com/36491850/113326231-41376600-92ce-11eb-986d-9783f106008c.png)

The vertex of the front most element is at 200 in Z. You say you are getting 215 which doesn't seem right. Could you draw the lens and click on the 2D-x button and post the result?

If I set the front element to a negative curvature 

lens = SphericalLens(SCHOTT.N_BK7, 200.0, -40.0, 400.0, 15.0, 20.0) 
Vis.draw(lens) 

this is what I get:

![image](https://user-images.githubusercontent.com/36491850/113329078-fd466000-92d1-11eb-9eca-bf8f4727e2f2.png)

This again looks like the expected result. Not sure why you are unable to get negative curvature.

**Comment by cdhf** [comment]
@BrianGun: With regard to differences to Zemax, I get the same drawing that you have. I guess I simply have a different expectation! In Zemax I get this drawing for first surface r1=40 and second surface r2=400:

![image001](https://user-images.githubusercontent.com/1413583/113394219-20d3de00-9398-11eb-8825-b4695a328989.png)

The intersection of the front surface (black in the drawing) with the optical axis is at z=200 mm. The coordinate system in Zemax is right handed as well. It think the difference are two definitions that seem to be different in Zemax (and most other sequential raytracers and literature I know).

- A positive radius of curvature means that the center of the sphere is to the right of the surface. I guess in OpticSim this is just the other way around.
- The front surface of a lens is the first surface in the direction of travel of the rays, which is usually from left to right in positive z-direction.

**Comment by cdhf** [comment]
I think I see now why my first raytracing attempt was wrong. Without looking at the code in detail I assumed that the coordinate system the ray must be in when calling surfaceintersection is the same coordinate system used in Zemax. The local coordinate system for a surface in Zemax has its z=0 plane at the intersection of the surface with the optical axis. In the drawing above for the leftmost surface that would be a plane touching the black surface at its vertex point. In the raytracing equations in OpticSim the local coordinate system of the spherical surface seems to be centered at the sphere's center.

This code here gives me the intersection coordinates consistent with the NSC case and with a Zemax raytrace (just the first surface for now):

```
function mysys1()
    r1 = 400.0
    if1 = OpticSim.opticinterface(typeof(r1), N_BK7, Air)
    s1 = Sphere(r1; interface = if1)    
    # Q: No negative radius allowed? 
    r2 = 40.0
    if2 = OpticSim.opticinterface(typeof(r1), Air, N_BK7)
    s2 = Sphere(r2; interface = if2)
    [(200.0, s1), (15.0, s2)]
end

function myray1()
    ray = Ray([0.0, 0.0, 0.0], [0.0, 10.0, 200.0])
    OpticalRay(ray, 1.0, 0.55)
end

function trace(assembly::Vector{Tuple{T, S}}, r::OpticalRay{T,N}, temperature::T = T(OpticSim.GlassCat.TEMP_REF), pressure::T = T(OpticSim.GlassCat.PRESSURE_REF); trackrays::Union{Nothing,Vector{LensTrace{T,N}}} = nothing, test::Bool = false, recursion::Int = 0)::Union{Nothing,NoPower,LensTrace{T,N}} where {T<:Real,S<:Surface,N}
    if length(assembly) == 0
        return nothing 
    end
    if power(r) < POWER_THRESHOLD || recursion > TRACE_RECURSION_LIMIT
        return nopower
    end
    (t, surface) = first(assembly)
    o = origin(r)
    d = direction(r)
    println(d)
    rad = radius(surface)
    α = (t-o[3]-rad)/d[3]
    # transfer the ray to the local coordinate system centered at the center of the sphere
    rnew = Ray([o[1] + α * d[1], o[2] + α * d[2], zero(o[3])], d)
    intsct = surfaceintersection(surface, rnew)
    p = point(intsct)
    println("intsct: $p")
    println("referenced to (0,0,0): $((p[1], p[2], p[3]-rad+t))")
end
trace0(mysys1(), myray1())
```

**Comment by BrianGun** [comment]
@cdhf  another part of the confusion might come from the way that OpticSim does its ray tracing. Because OpticSim supports CSG operations ray surface intersections are not points; they are intervals. The intervals bound the interior of the object the ray is intersecting, i.e., any point on the ray between the upper and lower bounds of an interval is inside the object.

We're going to digress here for a few paragraphs to explain how OpticSim works internally. The intention is this will make it easier for you to understand how to modify it in a way that gives predictable and reliable results. At the end we will come back to your sequential ray tracing problem.

For example, if you intersect a ray with a sphere you will, in the most common case, get an interval bounded by the two intersections of the ray with the sphere. If the ray originates from inside the sphere the lower bound will be the origin of the ray and the upper bound will be the single intersection with sphere surface. More complex surfaces, such as Bezier patches, might have multiple disjoint intersection intervals.

For non-sequential ray tracing objects in OpticSim are described as CSG trees. Each node in the tree represents a boolean operation on the children of that node: intersection, union, and difference. For every ray CSG tree intersection the system traverses the CSG tree , applying the boolean operators to the one dimensional intervals returned by the intersection function. The result is a potentially disjoint union of intervals. 

For optical simulations we usually are only interested in the first intersection but that can't be determined until after the CSG operations have been evaluated.

To make the CSG tree for a simple 2 surface spherical lens using sphere primitives you can use two spheres S1, S2, and a cylinder C1. If front and back surfaces are both convex then the CSG tree for the lens would be S1 ∩ C1 ∩ S2. If the front surface is convex but the rear surface is concave then the CSG tree would be S1 ∩ C1 - S2. The system reverses the sense of inside/outside for the last element, S2, because it is being subtracted.

Alternatively you can use the SphericalCap primitive (in file SphericalCap.jl) @friggog mentioned. This acts more like a single hemisphere. To build a convex/concave lens the CSG operations would be S1 ∩ C1 ∩ S2, where S1 would be a spherical element for the first surface, C1 is a cylinder, and S2 is a spherical cap.

If you only want to make simple Zemax style lenses this CSG stuff may seem like unnecessary complexity. But it is very useful when modeling more complex lens structures, which is what OpticSim was designed for.

Back to the problem you want to solve, doing sequential ray tracing. For this problem you only need surface intersections, not half spaces and CSG trees. For planes, Bezier and NURBS patches, Qtype, Zernike, etc., surfaces this is straightforward. Intersect the ray with the surface and take the closest intersection.

For spheres and cylinders it's more complex. Imagine you have a concave front surface. If the origin of the ray is sufficiently far away from the front surface the ray/sphere intersection will return an interval with two sphere surface intersection points. It is very likely the closest intersection is not the one you want. Instead you want the furthest intersection from the ray origin.  If the second surface is also concave then you want to return the closest intersection. The same issue arises for cylinders.

Maybe the cleanest way is to define a new surface type, Semisphere, which is a surface, not a half space. The semisphere surface would be that part of the sphere enclosed by a solid cone centered at the sphere origin.

You could specify the fraction of the sphere which makes up this surface with a solid angle and a vector, or a chord length that would correspond to the semidiameter of the lens, or perhaps make both types of constructors. 

Maybe something like this:

struct Semisphere{T<:Real}
   sp::Sphere
   direction::SVector{3} #this defines the center vector of the solid cone
   cos_solidangle::T #cosine of the solid angle of the semisphere
   interface::NullOrFresnel{T}
end

surfaceintersection(a::Semisphere, r::ray)
intsct = surfaceintersection(a.sp,ray)
# extract the intersection point(s) and put them in a vector, pts
for pt in pts
v = pt - origin(a.sp) #vector from origin to sphere surface intersection
if 0 < dot(a.direction, v) < a.cos_solidangle  
 #keep the point

#return an interval that matches the expectations of the closestintersection function. This might have one or two intersections.

Now when you use closestintersection on the returned interval you will always get the answer you expect.

Something like this, I haven't worked out all the details but it looks workable and not that much extra code.

**Comment by BrianGun** [comment]
just looked at your code again and realized there is another complication. 

CSGTree lets you associate a transformation with each node in the tree. When the tree is instantiated all these transformations are multiplied out and pushed to the leaf nodes of the tree, which contain the geometric primitives. 

The evalcsg function for LeafNode (CSG.jl line244) transforms the incoming ray into the coordinate frame of the geometric primitive and then calls surfaceintersection on the primitive with the transformed ray.

For non-sequential ray tracing you'll probably want to have a similar ability to associate transforms with each surface in the list of surfaces to be traced. Then you'd have some kind of eval function similar to evalcsg that would transform the incoming ray to the local coordinate frame before calling surfaceintersection on the primitive.

As you encounter issues with the API which confuse you please take notes and then share them with us so we can update the documentation.

**Comment by cdhf** [comment]
Hm, I will need a bit of time to digest this information. I've only cobbled together pure sequential raytracing for a few special applications so far, the implementation of a NSC raytracer is new to me. You are right, I definitely want to have some kind of transformation mechanism. This is a must for sensitivity analysis and tolerancing, which is really ugly in any optical design software I know, but really simple once you have this embedded in a full fledged programming language. 
My dream is a common high level system description that can be used as input for both NSC and SEQ simulation and optimization. I have to switch back and forth between both raytracing modes in Zemax quite a lot, which is very time consuming and also error prone.

**Comment by BrianGun** [comment]
We may be over engineering this. If the primary reason you want sequential ray tracing is to avoid the scattered rays cluttering the result then we can achieve that in the current system by adding another keyword argument to the trace function 

computescatteredrays = true

then when tracing FresnelInterface surfaces you set the keyword to false so it would never make a reflected ray from a FresnelInterface surface, which is 99% of refractive optical systems. It would just compute the refracted ray as in sequential ray tracing.

This would give you all the nice features of the non-sequential system we have now: CSG, transforms per element, and so forth. It would be less efficient than a pure sequential system but that may not be an issue for your application. And it wouldn't be much work.

Do you think this would meet your needs? It should be just a few lines of code. At line 180 in Fresnel.jl the code would add something like this:

#new code to approximate sequential ray tracing
if !computescatteredrays
    raydirection = refractedray(nᵢ, nₜ, normal, direction(incidentray))
else
 r = !test * rand()
    # assuming (powᵣ + powₜ) <= 1 (asserted in constructor)
    if r < powₜ
        # refraction
        raydirection = refractedray(nᵢ, nₜ, normal, direction(incidentray))
        raypower = powₜ * incident_pow
    elseif r < (powᵣ + powₜ)
        # reflection
        raypower = powᵣ * incident_pow
        raydirection = reflectedray(normal, direction(incidentray))
    else
        return nothing
    end
end

**Comment by cdhf** [comment]
@BrianGun 
I've realized pretty much the same yesterday evening. The part of the sequential mode in Zemax optics designers need are the analysis methods only available in this mode. Once you can easily trace a ray through a system and ignore ghosts and scattered light, things like ray aberration plots, MTF and all the other stuff can be calculated just as easily. With your proposed change the raytracing engine would already be basically feature complete.

And I think quite a bit of performance can be retrieved by passing into the trace function knowledge on the order in which objects can be hit.

So something like this in the trace function

```
# raypath is something like [(:E, 1), (:E, 2), (:R, 1)]
function trace(...; raypath = []}              
   ...
   closestintersection(assembly, r, raypath)
   ...
   res = trace(...; raypath = raypath[1:end])
```

And closestintersection would check for a nonempty raypath, and if it finds one it will calculate the intersection just for this element.

If needed I guess one could extend this by some way to index into the CGS tree of individual objects. At this point I guess there will not be too much of a performance hit anymore.

It seems to me that together with the additional flag to avoid ray splitting this would solve the problem neatly. In fact it makes some typical stuff like cardinal points calculation or pupil aberration stuff really easy, since you don't have to invert surfaces and distances when tracing rays forward and backwards through the system or part of if. Plus you avoid all the nasty coordinate system issues once you add folding mirrors.

Maybe you know this already, but there is a feature in Zemax NSC mode similar to this. For each object you can define a list of other objects that are considered during raytracing. This can speedup simulations considerably if you have many objects. Problem is, of course, that the usability of this feature is so bad that you will certainly break your simulation later in the design process in ways that are hard to detect and debug.

**Comment by BrianGun** [comment]
@cdhf let me look at the code  more carefully. If it's as simple as we think then I'll make the change in the next few days. 

For now let's put efficiency to one side until it becomes clear that it is a problem. Our multithreading works quite effectively so if you have a beefy multicore machine your tracing speed might still be good even though we're doing more work than necessary.

**Comment by cdhf** [comment]
@BrianGun If you mean the change to the processinterface function, I realized that there is a really important use case for me where a flag to switch of reflection alone is not general enough. If you have a system with beamsplitters, both reflection and refraction path need to be analyzed deterministically. You have to be able to switch beamsplitter elements from purely reflective to purely refractive depending on the path you are analysing. A lot of the systems I am working on are like this.

It's possible to work around this by manually unfolding paths and adjusting transmission/reflection coefficients on a case by case basis. However, at some point this will become cumbersome.

Maybe it is more sensible to make the decision of whether an interface should deterministically refract, reflect or randomly scatter when the element is defined and not when a ray is traced through the system? A user would then write a lens assembly in a function parametrized by the behaviour of the interfaces, and the raytracing behaviour would be just another multi configuration like lens positions in a zoom lens.

**Comment by BrianGun** [comment]
@cdhf that sounds like a reasonable idea. Do you want to take a crack at defining the interface? We can worry about the details of how to do it after we know what functions we are going to add.

We could add another type to the OpticalInterface type signature, something like this:

        abstract type Reflect
        abstract type Refract end
        abstract type ReflectAndRefract end
        abstract type ReflectOrRefract end
        
        RaySplitting = Union{Reflect,Refract,ReflectAndRefract,ReflectOrRefract}
        
        struct FresnelInterface{S<:RaySplitting,T<:Real}

Then when you create a FresnelInterface you specify the type:

intfc = FresnelInterface{Reflect,Float64}(....) #reflecting only
intfc = FresnelInterface{Refract,Float64}(....) #refract only 
intfc = FresnelInterface{ReflectAndRefract,Float64}(....) #reflect and refract ,i.e., spawn two rays at this optical surface
intfc = FresnelInterface{ReflectOrRefract,Float64}(....) #generate one ray, reflected or refracted, chosen stochastically


and the processintersection function for eachOpticalInterface type would have multiple versions displatching on the RaySplitting type:

processintersection(intfc::FresnelInterface{Reflect,T},....)  #just do reflection
processintersection(intfc::FresnelInterface{ReflectAndRefract,T},......) #do reflection and refraction

etc. 3 out of the 4 processintersection functions would return only 1 ray but the fourth would return two rays.

Is this something along the lines of what you were thinking?

Would you like to take a stab at implementing this? I can help you work through the code.

**Comment by cdhf** [comment]
Yes, that's what I mean. I will try to implement this and come back once I have something. May take some days, because my workload is pretty high at the moment.

**Comment by friggog** [comment]
I would avoid defining a subtype of OpticalInterface which is parameterised by any more types than the datatype. It's not possible to infer these additional type parameters in all cases so the compiler ends up with type ambiguities which cause runtime allocations and ruin performance. You can instead have these as members of the interface and just use flags of known size e.g. (sorry if the syntax isn't right I haven't written julia in a while)

```julia
@enum SequentialInterfaceMode SequentialInterfaceReflect SequentialInterfaceRefract SequentialInterfaceAbsorb

struct SequentialInterface{T<:Real} <: OpticalInterface{T}
   mode::SequentialInterfaceMode
end

function trace(interface::SequentialInterface, ...)
    if interface.mod == SequentialInterfaceRefract
        ...
    elif ...
end
```

It's not the typical julia way of doing things and therefore not as neat, but in this case is necessary to retain performance.

**Comment by BrianGun** [comment]
Alternatively we could add the extra type to OpticalInterface. OpticalInterface isn't used in that many places in the code so not too horrendous a change.

**Comment by cdhf** [comment]
There is now some code to look at [here](https://github.com/cdhf/OpticSim.jl/tree/fakeseq). It is a very small change, only to play with the API. In particular no documentation yet...

I have not touched anything except the FresnelInterface for now, because I haven't taken the time to make sure I understand the code completely. But I made default arguments for the FresnelSurface constructors such that there should be no change in behaviour for already existing code.

**Comment by BrianGun** [comment]
@cdhf 

This looks good, clean and simple, seems to do the job.

Have you tried creating a simple optical system using the new code to see how it feels in use? Maybe a set of half silvered mirrors with the reflection/transmission bit set to the appropriate values? Then you could see if the results match your expectations. 

I suppose the other thing we need to do soon is add multiple detectors to an optical system, since this is something you will probably need as well. 

Also, I noticed you didn't include ReflectAndTransmit in the Enum type. Is this because you feel nobody will ever want to do this? I don't have an opinion either way - we can leave it the way you propose until someone makes a good case that this last mode is useful.

It would be good to add an explanation of the InterfaceMode  to the docstring for FresnelInterface. Include the justification for the new mode, show an example with the default value, and one with the InterfaceMode set to Reflection. That should be enough to get people going.

In your code you modify the value of the r variable to cause either the reflection or transmission path to be chosen in the conditional a few lines below. It would be good to add documentation to the code along the lines of:

 if interfacemode(opticalinterface) == Reflect #set the value of r so that only a reflection ray will be generated

        r = powᵣ / 2 + powₜ
    elseif interfacemode(opticalinterface) == Transmit #set the value of r such that only a refraction ray will be generated.
        r = zero(T)
    else
  
The code requires a bit of head scratching to understand otherwise. An alternative would be to modify the conditional of the ray generation so it explicitly branches on the InterfaceMode variable, rather than indirectly based on the value of r. That might be easier to understand for new users.

Do all the existing unit tests pass with the new code?

**Comment by cdhf** [comment]
Hi,
I made a test system with a beamsplitter and a mirror and a large detector to work around the single detector issue. That worked fine for me, and the interface is reasonably easy to use. Parts before a beamsplitter are put in one function, and the different paths after the beamsplitters are put into other functions. This neatly matches many typical optomechanical designs and would therefore be done anyway. 

The unit tests all run fine. 

For me ReflectAndTransmit is real raysplitting. I did not want to implement this at the moment, because I haven't looked into the details of how a raytrace is ended and how to control the total memory used. I think Ray splitting can be useful in the analysis of ghost reflections and maybe diffractive elements, but I tend to avoid it if possible in Zemax because you quickly run into of memory conditions if you are not careful.

I will incorporate documentation and rework the branching code for clarity following your suggestions and open a pull request.
