### ISSUE TITLE
Use relative imports in AGFGlassCat.jl

### ISSUE THREAD

**Issue by friggog** [microsoft/OpticSim.jl#69]
Currently the absolute path is written to AGFGlassCat.jl, it would be better to just use relative paths e.g. "NIKON.agf" for the includes.

It would also be great to have some clarity around the install/build process to help with setup on AML. I have jobs (almost) working when running from a clone of this repo, but ideally we'd (also) support downstream packages with OpticSim as a dependency, in which case we'll need to install OpticSim through Pkg on the VM. Will the build just happen automatically in this case and generate the glass stuff as needed?

**Comment by alfredclwong** [comment]
Been busy with hardware stuff so I haven't had much time for OpticSim lately! Although I believe I did manage to write a short description of the build process in the docs. It's also standard Julia - builds, including downstream packages, will be triggered by Pkg.build or Pkg.add.

I can change to relative paths in the build script. This would mean passing "data" instead of JL_DIR to generate_jls() in build.jl L45. You can see why I went with absolute paths, as we also run mkdir() from deps/ in order to ensure the data directory exists. Is this causing an issue in cloud runs?

**Comment by friggog** [comment]
Seems even simpler: https://github.com/microsoft/OpticSim.jl/pull/71/commits/3ff429438248a8c9f729b67a91efa39617f0fee8

The issue was only when running from a clone of this repo as the source files are uploaded as a snapshot meaning the absolute paths broke stuff.

Building seems to work fine on the cloud runs when OpticSim is a dependency, I sometimes get errors in the logs (and locally) for build/precompilation but it doesn't seem to affect things and it's not clear what package is the issue?

**Comment by alfredclwong** [comment]
Ah yes I forgot that AGFGlassCat.jl was in data/ already, thanks.

That's what I'm a bit confused about - clones from the repo shouldn't contain AGFGlassCat.jl. Is there a central controller that clones the repo, builds the package, and then distributes the generated code to workers?

I see those ambiguous errors too in Julia 1.6. Not sure how to find out which package is at fault.

**Comment by friggog** [comment]
I cloned it to my local machine then ran `] build` to generate the files so I can open the REPL with `--project` inside the OpticSim.jl directory and use the package from there. With AML a snapshot of your "source directory", in this case my cloned OpticSim.jl directory, is uploaded and the script executed within that - hence the problem.

If OpticSim is a dependency within a separate project where that project's source directory is uploaded then there isn't a problem because OpticSim gets installed through Pkg on the VM and built there.

**Comment by alfredclwong** [comment]
Yeah I'm agreed on the relative paths. I was just referring to the fact that it was possible to change the AGFGlassCat.jl location due to the flexibility I wrote into the original code, so we need to remove that option (see 7867d51).

As for flexibility of relative vs absolute, the fact that the former supports both of those use cases proves your point!

**Comment by BrianGun** [comment]
@alfredclwong @friggog is this ready to go? Did one of you want to make a pull request for this?

**Comment by friggog** [comment]
It’s fixed in #71 which isn’t finished yet - doesn’t seem like an urgent fix on it’s own though, just needed it to run on the cloud
